### ISSUE TITLE
L2TP: Mod einbauen, der sich zum Gateway mit den wenigsten Tunneln verbindet

### ISSUE THREAD

**Issue by MPW1412** [FreiFunkMuenster/site-ffms#48]
Moin,

derzeit verbindet sich unsere L2TP-Firmware einfach zum ersten Gateway, das klappt und probiert diese von oben nach unten durch.

Daher hängen fast alle Knoten an einem Gateway und das jeweils andere hat kaum Verbindungen.

Dies sollten wir ändern, dazu müsste man sich anschauen, wie Paulo oder wie andere Communities das gemacht haben.

**Comment by paulinsche** [comment]
Ich würde heute nicht mehr die Modifikationen vom ffrl einbauen. Dank der Schwächen von batman würde ich alles schön auf einem vpn-server laufen lassen.

**Comment by HellMar** [comment]
Das hat sich erledigt oder?

**Comment by MPW1412** [comment]
Genau, der Algorithmus für die Nutzung ist repariert.
