### ISSUE TITLE
Spezifische Downloadpfade je Domäne

### ISSUE THREAD

**Issue by descilla** [FreiFunkMuenster/site-ffms#50]
Das jüngste Problem während der Knotenmigration ( https://forum.freifunk-muensterland.de/t/probleme-unfall-bei-knotenmigration-von-domaene-02-nach-domaene-12-und-domaene-13/1141/13 ) hat gezeigt, dass es nicht ausreichend ist allein anhand des IPv6 Präfixes zu entscheiden welche Firmware ein Knoten bekommt.

Zwar lässt sich der Firmware-Downloader für eine Domäne während des Migrationsprozesses "abschalten", jedoch ist das keine Dauerlösung.

Nach dem Migrationsprozess werden die geo-präfixe ja wieder aktiviert. Wenn nun jedoch eine Brücke zwischen zwei Domänen entsteht, passiert das selbe. Wir haben also ein nicht vorhersagbares Verhalten, welche Firmware ein Knoten lädt, wenn zwei Domänen gebrückt sind.

Als Schutzmechanismus dagegen schlage ich vor für jede Domäne spezifische Download-Pfade zu hinterlegen. Alternativ könnte man für jede Domäne einen anderen, eindeutigen DNS Namen für den Firmware-Server in die Firmware einbringen.

**Comment by MPW1412** [comment]
Die Gefahr besteht nicht, wenn überall dieselbe Firmwareversion verwendet wird.

**Comment by HellMar** [comment]
Wird zusammen mit der nächsten Gluon Version umgesetzt.

**Comment by HellMar** [comment]
Umgesetzt in Firmware Version 1.2.2
